# Generated by Django 3.0.5 on 2020-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='date_comleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
