# Generated by Django 3.0.5 on 2020-10-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201004_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapp',
            old_name='date_comleted',
            new_name='date_completed',
        ),
    ]
